from playwright.sync_api import sync_playwright
import re
import pytest
import time
import json

def test_design_padrao() -> None:
    with sync_playwright() as p:
        with open('config.json') as config_file:
            config = json.load(config_file)
    browser = p.chromium.launch(headless=False) 
    context = browser.new_context()
    page = context.new_page()
    page.goto(config['site'])
    page.get_by_label("Nome de usuário ou e-mail").fill(config['usuario'])
    page.get_by_label("Senha").click()
    page.get_by_label("Senha").fill(config['senha'])
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Padrão").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

 
def test_design_pink(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=lwC5TbgnzkxrhiI3Y62EKC32rf4M3ofNa37J4-iRFH4&code_challenge=Hc0gyOgGo8pRGqzfu7kSGWRZbUkFHl4Bgp_cEk2hdb4&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").click()
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_role("link", name="Design").click()
    page.locator("label").filter(has_text="Rosa").click()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_test_id("avatar").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

def test_design_red(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=lwC5TbgnzkxrhiI3Y62EKC32rf4M3ofNa37J4-iRFH4&code_challenge=Hc0gyOgGo8pRGqzfu7kSGWRZbUkFHl4Bgp_cEk2hdb4&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").click()
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Vermelha").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

def test_design_orange(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Laranja").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

def test_design_yellow(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Amarela").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

def test_design_blue(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Azul").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_test_id("avatar").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

def test_design_violet(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Violeta").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()

def test_design_cinza(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Cinza").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

def test_design_reset(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_role("button", name="Resetar configurações").click()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

def test_design_change_text_black(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Preto").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.get_by_role("heading", name="Sair").click()

def test_design_change_text_white(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.get_by_label("Branco").check()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

def test_design_custom(playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://dev.mrce.sistematodos.com.br/")
    page.goto("http://auth.dev.mrce.sistematodos.com.br:8080/realms/motor-rce/protocol/openid-connect/auth?client_id=motor-rce-front&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Fdev.mrce.sistematodos.com.br%2Fapi%2Fauth%2Fcallback%2Fkeycloak&state=WTdXREZW8-Xp-3SCNUH6WlHi5Ft5wFDEZpz4DYheWQo&code_challenge=wg-CwbwaDukjEvh1nOHEFYhQ1_owESmZErzCBvQaWlo&code_challenge_method=S256")
    page.get_by_label("Nome de usuário ou e-mail").fill("victor.qa")
    page.get_by_label("Nome de usuário ou e-mail").press("Tab")
    page.get_by_label("Senha").fill("Victor001")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("button", name="Sign in with Keycloak").click()
    page.get_by_role("link", name="Design").click()
    page.locator("label").filter(has_text="Personalizada").click()
    page.get_by_label("Color").locator("div").first.click()
    page.get_by_label("Color").locator("div").first.click()
    page.get_by_label("Hue").locator("div").first.click()
    page.get_by_label("Hue").click()
    page.get_by_label("Color").locator("div").first.click()
    page.get_by_role("button", name="Salvar alterações").click()
    page.get_by_role("link", name="Indicadores").click()
    page.get_by_test_id("avatar").locator("svg").click()
    page.locator("div").filter(has_text=re.compile(r"^Sair$")).click()

